const test = [
    {question: 'How old are you?',
    answer: ['I have 16', 'I am 16', 'I have 16 years', 'I am 16 years']},
    {question: 'Are you having a nice time?',
    answer: ['Yes, I’m nice.', 'Yes, I’m having it.', 'Yes, I am.', 'Yes, it is.']},
    {question: 'Could you pass the salt please?',
    answer: ['Over there.', 'I don’t know.', 'Help yourself.', 'Here you are.']},
    {question: 'Yesterday I went __________ bus to the National Museum.',
    answer: ['on', 'in', 'by', 'with']},
    {question: 'Sue and Mike __________ to go camping.',
    answer: ['wanted', 'said', 'made', 'talked']},
    {question: 'Who’s calling, please?',
    answer: ['Just a moment.', 'It’s David Parker.', 'I’ll call you back.', 'Speaking.']},
    {question: 'They were __________ after the long journey, so they went to bed.',
    answer: ['hungry', 'hot', 'lazy', 'tired']},
    {question: 'Can you tell me the __________ to the bus station?',
    answer: ['road', 'way', 'direction', 'street']},
    {question: '__________ you remember to buy some milk?',
    answer: ['Have', 'Do', 'Should', 'Did']},
    {question: '- Don’t forget to put the rubbish out. - I’ve __________ done it!',
    answer: ['yet', 'still', 'already', 'even']},
    {question: 'You don’t need to bring __________ to eat.',
    answer: ['some', 'a food ', 'many', 'anything']},
    {question: 'What about going to the cinema?',
    answer: ['Good idea!', 'Twice a month.', 'It’s Star Wars.', 'I think so.']},
    {question: '- What would you like, Sue? - I’d like the same __________ Michael please.',
    answer: ['that', 'as', 'for', 'had']},
    {question: '__________ people know the answer to that question.',
    answer: ['Few', 'Little', 'Least', 'A little']},
    {question: 'It’s not __________ to walk home by yourself in the dark.',
    answer: ['sure', 'certain', 'safe', 'problem']},
    {question: '__________ sure all the windows are locked.',
    answer: ['Take', 'Have', 'Wait', 'Make']},
    {question: 'I’ll go and __________ if I can find him.',
    answer: ['see', 'look', 'try', 'tell']},
    {question: 'What’s the difference __________ football and rugby?',
    answer: ['from', 'with', 'for', 'between']},
    {question: 'My car needs __________ .',
    answer: ['repairing', 'to repair', 'to be repair', 'repair']},
    {question: 'Tim was too __________ to ask Monika for a dance.',
    answer: ['worried', 'shy', 'selfish', 'polite']},
    {question: 'I haven’t had so much fun __________ I was a young boy!',
    answer: ['when', 'for', 'during', 'since']},
    {question: 'Sorry, I don’t know __________ you’re talking about.',
    answer: ['that', 'what', 'which', 'why']},
    {question: 'I’m afraid you __________ smoke in here.',
    answer: ['could not', 'don’t have to', 'are not allowed to', 'can’t be']},
    {question: 'Everyone wanted to go out __________ John.',
    answer: ['apart', 'unless', 'however', 'except']},
    {question: 'Honestly! I saw a ghost! I’m not __________ it up!',
    answer: ['having', 'laughing', 'making', 'joking']},
    {question: 'Eat everything up! I don’t want to see anything __________ on your plate!',
    answer: ['left', 'missing', 'put', 'staying']},
    {question: 'Take the A20 __________ the roundabout, then turn left.',
    answer: ['right', 'as far as', 'along', 'heading north']},
    {question: 'I really hope you can find a __________ to this problem.',
    answer: ['result', 'way', 'conclusion', 'solution']},
    {question: 'Could you watch my bag while I go and get a cup of tea?',
    answer: ['Of course!', 'Never mind.', 'If you don’t mind.', 'It doesn’t matter.']},
    {question: 'In my country, it is __________ the law to watch an X-rated film if you are under eighteen.',
    answer: ['under', 'against', 'over', 'beyond']},
]

 export default test